### ISSUE TITLE
sendRequest adds ? in URL

### ISSUE THREAD

**Issue by hjone72** [invoiceninja/sdk-php#10]
Hi,

When using archive, delete, and restore an error is thrown. `"error": "Action [archive?] is not supported"`

This is because of https://github.com/invoiceninja/sdk-php/blob/master/src/InvoiceNinja/Models/AbstractModel.php#L139 appends a ? separator when there is already an "?action=$action" in the URL.

Thanks,

**Comment by hillelcoren** [comment]
Thanks for catching this, are you able to create a pull request with your fix?

**Comment by hjone72** [comment]
My bad. I thought I had created the pull request.

**Comment by hillelcoren** [comment]
Thanks for your help!
