### ISSUE TITLE
Create user via API

### ISSUE THREAD

**Issue by danielspeicher** [invoiceninja/sdk-php#106]
Hello,

we are using this SDK and we need help:

We want to synchronize users from another backend system and we want to use the API via this SDK. How can we create a user?

We get an error message: `Invalid password`. We are using a valid API token, because to get a list of users works.

Thanks for your help.

**Comment by turbo124** [comment]
Some routes are protected by password. To access that particular route you will need to add a header into the request as follows.


```php
->addHeader(['X-API-PASSWORD' => 'your_password])
```
or
```php
->addHeader(['X-API-PASSWORD-BASE64' => 'your base 64 encoded password']);
```

**Comment by hillelcoren** [comment]
In the past we've found people who automate user management may be reselling the app, I suggest reviewing the license to ensure your use case is ok.

https://invoiceninja.github.io/en/legal/license/
