### ISSUE TITLE
How to set event_id on creation?

### ISSUE THREAD

**Issue by AugmentBLU** [invoiceninja/sdk-php#14]
Hello,

The SDK is really helpful, I'm just wondering how we set the event_id in the Subscriptions table? 

I want to register a subscription that related to `EVENT_CREATE_PAYMENT` but it defaults to event_id 1.

Thanks

**Comment by hillelcoren** [comment]
Can you share you code, are you using `Payment::subscribeCreate(...);`

**Comment by AugmentBLU** [comment]
I managed to solve this, I didn't realise I was using `Client::subscribeCreate(...);`
