### ISSUE TITLE
Event on Overdue Invoice

### ISSUE THREAD

**Issue by AugmentBLU** [invoiceninja/sdk-php#16]
Hello,

I want to be able to disable an account in my app if an invoice is past due, basically the user needs to keep up to date with their monthly subscription or their account is disabled.

I'm not quite sure how best to do this or if there's an event that is triggered when an invoice is past due. Perhaps if I set the 3rd email notification to be past the due date, that could be used to also disable the account? However, I'm not how I could do this with the SDK or subscriptions. Any pointers how that could be done?

Thanks

**Comment by hillelcoren** [comment]
Not sure, this isn't currently supported. You may just need to load the data daily and check.

**Comment by AugmentBLU** [comment]
Yeah, I just created a new function in the ContactMailer.php file to check the external DB and set the account to disabled based on the reminder being `reminder3`. It works... just wonder how I can do this without it being overwritten with each composer update though.
