### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by lbausch** [invoiceninja/sdk-php#19]
The latest tagged version (0.3) still suffers from the "Ambiguous class resolution" issue when requiring the sdk-php with Composer (`"InvoiceNinja\Models\Product" was found in both ...`).

**Comment by hillelcoren** [comment]
Has this issue been fixed? Can you post a link to the commit.

**Comment by lbausch** [comment]
It should be 2839d047c73d6ae3708398eeb1e7bec2d8f84511

**Comment by hillelcoren** [comment]
Thanks!
