### ISSUE TITLE
Set VAT on invoice

### ISSUE THREAD

**Issue by marcoboers94** [invoiceninja/sdk-php#2]
How can I set the VAT on the created invoice? 
Or make make a certain tax rate the standard of a new invoice?

**Comment by hillelcoren** [comment]
You should be able use:

    $invoice = new Invoice();
    $invoice->client_id = 1;
    $invoice->addInvoiceItem('Item', 'Notes...', 10);
    $invoice->tax_name1 = 'VAT';
    $invoice->tax_rate1 = 17;
    $invoice->save();
