### ISSUE TITLE
Field 'transaction_reference' is missing the expense object

### ISSUE THREAD

**Issue by alexbogias** [invoiceninja/sdk-php#22]
Can you please include this field in your API

**Comment by hillelcoren** [comment]
Sure, we'll add it in our next release.

**Comment by oMikR0n** [comment]
Could you please let me know how I can add it myself? Is it easy?

**Comment by hillelcoren** [comment]
You just need to add it to this file:

https://github.com/invoiceninja/invoiceninja/blob/master/app/Ninja/Transformers/ExpenseTransformer.php

**Comment by oMikR0n** [comment]
Thanks a lot @hillelcoren !
