### ISSUE TITLE
Get task rate

### ISSUE THREAD

**Issue by fibis** [invoiceninja/sdk-php#27]
Would it possible to get the task rate per task via the API when you call `getTasks()`?

**Comment by fibis** [comment]
@hillelcoren Would it be a problem if  I would try to implement this? I have analyzed the code and it seams, that it is pretty easy to implement in invoiceninja.

**Comment by hillelcoren** [comment]
Can you please explain more clearly the changes.

**Comment by fibis** [comment]
Never mind, my idea didn't work, to add an property to the output of the API for each task with the value of the geRate function. Would still be nice, if this could be implemented 😊
