### ISSUE TITLE
Uploading a Document to an Invoice?

### ISSUE THREAD

**Issue by mprythero** [invoiceninja/sdk-php#32]
Hello -

I was curious if it was at all possible to upload a document with this sdk? We generate specialized documents on our end and would like to automatically upload them as included documents before emailing them off to the client. I'd certainly appreciate any help or suggestions on how we might be able to get that working.

Thanks -
Matt

**Comment by hillelcoren** [comment]
It isn't supported with the SDK but should be possible using the API
