### ISSUE TITLE
Doing a refund?

### ISSUE THREAD

**Issue by noezdev** [invoiceninja/sdk-php#33]
How can i refund a payment with the api?

**Comment by hillelcoren** [comment]
I don't believe it's currently supported by the API

**Comment by hillelcoren** [comment]
Note: you can deleted a payment which would restore the invoice balance.

**Comment by noezdev** [comment]
That should be a problem after some time, if you lose the perspective.

**Comment by noezdev** [comment]
Did not work ❌

**Comment by hillelcoren** [comment]
Sorry, it isn't supported.

Note: the payment remains in the system but it marked as deleted.

**Comment by noezdev** [comment]
Okay that should fit my needs. Thanks.
