### ISSUE TITLE
Emailing Invoice in Separate Event after Creation

### ISSUE THREAD

**Issue by mprythero** [invoiceninja/sdk-php#35]
I was curious if it was possible to email an invoice after it has been already been saved.

For example say in one function I successfully create an invoice through a function called createInvoice

```
$invoice = $client->createInvoice();
		$invoice->addInvoiceItem('$chargeCategory', $chargeSubCategory, $billedAmount);
		$invoice->invoice_date = $charge->date->format('Y-m-d');
		$invoice->due_date = $charge->due_date->format('Y-m-d');
		$invoice->save();
```

This works just fine, but I was curious if there was a way to be able to email the invoice after the fact. I was trying it out because sometimes our customers require documentation to go along with the billing, and sometimes that isn't readily available. So what I would like to be able to do is separate the email process, but through the below test function, it doesn't seem to want to send, and was wondering if there was another way about doing this...

```
$invoice = Invoice::find($charge->billingUploadStatus->recordSpecificID);
		$invoice->email_invoice = true;
		$invoice->save();
```

The connections are successfully made I should note, it's just that the invoice remains a draft and doesn't send out to the contacts of the client...

Thanks!

**Comment by TheJenne18** [comment]
Hi, I've created an send_invoice method: https://github.com/invoiceninja/sdk-php/pull/49.
