### ISSUE TITLE
Deleting Invoice Items

### ISSUE THREAD

**Issue by mprythero** [invoiceninja/sdk-php#37]
I was curious if it might be possible to delete all invoice items on an invoice and start again. I know it might not be the best way around it, but for a lot of our invoices, we only have one item. It would be nice if we could just clear out the invoice if say another item is added, or pricing is changed on our backend system, to be able to update the invoice and the line items all in one swoop. 

If this is not possible, could it be through an implementation of sorts? 

Thanks!

**Comment by hillelcoren** [comment]
You should be able to simply update the invoice?
