### ISSUE TITLE
No support for creating a quote?

### ISSUE THREAD

**Issue by thinckx** [invoiceninja/sdk-php#38]
Hi!

According to my findings, the sdk currently doesn't support creating quotes, am I correct? I never contributed to open source before, but I'd be glad to do so.

Are you accepting PR's? 

Thomas

**Comment by hillelcoren** [comment]
You can use the /invoices route to create a quote

**Comment by thinckx** [comment]
Yes, in the API you mean? I'm talking about the SDK, where I'd do something like this:

```
$client = new Client('hello@acme.org');
$client->save();

$is_quote = true;
$client->createInvoice($is_quote);
```

**Comment by hillelcoren** [comment]
I think something like this may work:

```
$quote = $client->createInvoice();
$quote->is_quote = true; 
```

**Comment by thinckx** [comment]
Ah yes indeed. Perfect.

Thanks @hillelcoren!
