### ISSUE TITLE
Can't create new product with sdk-php

### ISSUE THREAD

**Issue by tpcarmen** [invoiceninja/sdk-php#39]
I'm using the "Invoice Ninja - v4.5.13 | White labeled" and trying to create a new product using php-sdk as:

$product = new Product("foo");
$product->save();

However it throws an error which I don't understand:

 [string:Exception:private] => 
    [code:protected] => 0
    [file:protected] => /opt/integration/vendor/invoiceninja/sdk-php/src/InvoiceNinja/Models/AbstractModel.php
    [line:protected] => 186
    [trace:Exception:private] => Array
        (
            [0] => Array
                (
                    [file] => /opt/integration/vendor/invoiceninja/sdk-php/src/InvoiceNinja/Models/AbstractModel.php
                    [line] => 78
                    [function] => sendRequest
                    [class] => InvoiceNinja\Models\AbstractModel
                    [type] => ::
                    [args] => Array
                        (
                            [0] => https:/www.terrys-service.com/in/api/v1/products?
                            [1] => {"id":null}
                            [2] => POST
                        )

                )

            [1] => Array
                (
                    [file] => /opt/integration/addProduct.php
                    [line] => 55
                    [function] => save
                    [class] => InvoiceNinja\Models\AbstractModel
                    [type] => ->
                    [args] => Array
                        (
                        )

                )

        )

Line 55 is the call to save().

I checked InvoiceNinja\Models\Product and it seems to be mostly empty, so I'm not sure if the API simply doesn't allow creating products, or if I have something misconfigured or not initialized, or if I need to pass in different or more parameters to the "new Product()" call.

Any suggestions? I can't seem to find any examples or docs for adding a new product, so I'm not sure I'm using this correctly.

Thanks!

Terry

**Comment by hillelcoren** [comment]
Try setting the product's product_key value

**Comment by tpcarmen** [comment]
Awesome!

Now I have 

	$product = new Product();
	$product->product_key = "foo";
	$product->save();

and it works!

Thank you for an absolutely spectacular product!
