### ISSUE TITLE
Error in RemoteModel

### ISSUE THREAD

**Issue by timo002** [invoiceninja/sdk-php#4]
I believe there is an error on line 36 of RemoteModel.php

```
33    public static function find($id)
34    {
35        $url = static::getRoute() . '/' . $id;
36        $data = static::sendRequest();
37
38        return static::hydrate($data);
39    }
```

Line 36 should be:
```
36        $data = static::sendRequest($url);
```

**Comment by marcoboers94** [comment]
This was fixed in (now) abstractModel.php

**Comment by timo002** [comment]
Hmm, I installed with composer, but my code is different from this code on github.
composer.json:
```
"invoiceninja/sdk-php": "^0.2.0"
```

**Comment by timo002** [comment]
I installed with
```
composer require invoiceninja/sdk-php
```

But that gave me version 0.2.0.

I changed the composer.json file to 'dev-master' and now it's fine!

**Comment by hillelcoren** [comment]
I've created a new release which includes this fix.
