### ISSUE TITLE
Inserting Time Logs to a Task

### ISSUE THREAD

**Issue by cheey2003** [invoiceninja/sdk-php#41]
Hi there,

May I know whether there is any method in the API which allows inserting time logs to a task?

Regards,

Patrick

**Comment by hillelcoren** [comment]
Yes, the time logs can be set with the API. 

The data is stored as a mutl-dimensional array of start/end times.

**Comment by cheey2003** [comment]
Great to hear that, @hillelcoren; thank you so much for the info.

May I know is there any example which I can refer to on how to insert the time logs?

**Comment by hillelcoren** [comment]
Sorry, I don't have an example. Here's the relevant code:

https://github.com/invoiceninja/invoiceninja/blob/master/app/Http/Controllers/TaskApiController.php#L113

Setting time_log will use raw data or you can use time_details for formatted data (this is used to support Zapier).

**Comment by cheey2003** [comment]
Thanks a lot, @hillelcoren - I will give it a try ;)

**Comment by andreapx** [comment]
>I will give it a try ;)
Hi @cheey2003 did you succeed inserting time logs? If yes...how?
Thanks!

**Comment by cheey2003** [comment]
> > I will give it a try ;)
> > Hi @cheey2003 did you succeed inserting time logs? If yes...how?
> > Thanks!

Unfortunately I was not able to make any progress and gave up :(

**Comment by andreapx** [comment]
@turbo124 just out of curiosity, why did you close this issue? Is this now possible?
Thanks!

**Comment by turbo124** [comment]
Hi there, 

We are no longer developing features for the v4 platform. This should be possible with our SDK for v5

**Comment by andreapx** [comment]
Got it, thanks for the explanation!
