### ISSUE TITLE
Failing to Make Request

### ISSUE THREAD

**Issue by smartified** [invoiceninja/sdk-php#42]
I am using the SDK in a laravel project, whenever i try to make a request using the browser. I get the error 

what could be the problem?

**Comment by hillelcoren** [comment]
I'm not sure, it looks like the SDK is looking for the account_gateways table which belongs to the app database. 

Note: You may want to remove the screenshot as it contains the token to access your account.

**Comment by smartified** [comment]
It's fine, that is a self hosted, local test site. I have removed it anyway. When i use the console it works properly, so i am not sure why it's trying to use the apps database instead of making a request to the invoice ninja api.
