### ISSUE TITLE
Do not append slash to route when requesting /api/v1/static

### ISSUE THREAD

**Issue by d00p** [invoiceninja/sdk-php#47]
Just came across this. The `Models/Statics.php` file appends a trailing slash at the end of the route which causes the response to be a `301 Moved Permanently` and tells that the document has moved to `/api/v1/static?`

Works after the following adjustment:

```diff
    public static function all()
    {
-        $url = static::getRoute() . '/';
+        $url = static::getRoute();
        
        return static::sendRequest($url, false, 'GET', true);
    }

**Comment by hillelcoren** [comment]
Thanks for catching it, do you want to submit it as a PR?

**Comment by d00p** [comment]
Sure no problem
