### ISSUE TITLE
E-mail invoice not sending invoice as attachement

### ISSUE THREAD

**Issue by timo002** [invoiceninja/sdk-php#5]
Hello,

I'm creating in invoice like this:
```
$invoice = $client->createInvoice();
$invoice->invoice_data = $invoice_date;
$invoice->due_date = $due_date;
$invoice->tax_name1 = "BTW Hoog";
$invoice->tax_rate1 = 21;
$invoice->email_invoice = true;

$invoice->addInvoiceItem('key', 'description', 25, 1);

$invoice->save();
```
Now this should send an e-mail to the customer, and it does. But it will not attach a PDF of the invoice to the e-mail. How will I be able to do that?

**Comment by marcoboers94** [comment]
Have you enabled the setting in the invoice ninja backend? 
Onder instellingen -> emailinstellingen -> PDF als bijlage toevoegen in e-mailberichten
Under settings -> email settings -> attach pdf to email

**Comment by timo002** [comment]
Yes, when I e-mail the invoice from invoiceNinja self it invoice is attached. The settings are:
![image](https://cloud.githubusercontent.com/assets/6170938/21533148/cf7429ee-cd57-11e6-86dc-fde9cb2631ad.png)

**Comment by hillelcoren** [comment]
Is your app publicly accessible? We use phantomjscloud.com to generate the PDF if it isn't shown on screen before emailing,

**Comment by marcoboers94** [comment]
What happens when you use this to send the email
```
curl -X POST ninja.dev/api/v1/email_invoice -H "Content-Type:application/json" -d '{"id":1}' -H "X-Ninja-Token: TOKEN" -H "X-Requested-With: XMLHttpRequest"
```
From https://www.invoiceninja.com/api-documentation/

**Comment by timo002** [comment]
@hillelcoren - The app in on my local vagrant machine. Sending the invoice from invoice ninja (invoices/258/edit) is working fine and attaching the PDF.

@marcoboers94 - Running it with that URL also doesn't attach the PDF.

**Comment by hillelcoren** [comment]
That would explain why phantomjscloud.com isn't working. 

We're looking into adding support for a local phantomjs solution.

**Comment by timo002** [comment]
@hillelcoren - That means it would work on my production environment?

**Comment by hillelcoren** [comment]
Yes, it should.

**Comment by timo002** [comment]
Indeed, on my production environment it seems to be working fine! Thanks!
