### ISSUE TITLE
Credit support

### ISSUE THREAD

**Issue by hjone72** [invoiceninja/sdk-php#6]
Hi,

Would it be possible to add Credit support to this?

Thank you,

**Comment by hillelcoren** [comment]
Sure, I'll look into it.

**Comment by hjone72** [comment]
Hi,

I updated my version with the changes from the commit. I am seeing a message "Route does not exist". Am I missing something to get this going?

Thanks,

**Comment by hillelcoren** [comment]
It looks like the API doesn't support credits, we'll look into adding support in the future.

**Comment by hillelcoren** [comment]
I've checked in credit API support to the develop branch, this is now working for me:

```
   $credit = new Credit();
   $credit->client_id = 1;
   $credit->amount = 10;
   $credit->save();
```
