### ISSUE TITLE
Any way to download the Attachments to an expense via API?

### ISSUE THREAD

**Issue by cmorillo** [invoiceninja/sdk-php#62]
Hi there,

The SDK is pretty good, I am using it for Invoice Ninja - v4.5.24 so I would like to download the documents attached to an expense just like I do for the invoices.

Is it possible?

Cheers

**Comment by hillelcoren** [comment]
Sorry, I don't think it's currently supported using the SDK. You'd need to use the API directly.

**Comment by hillelcoren** [comment]
I think this is the same as #32

**Comment by cmorillo** [comment]
Cheers
