### ISSUE TITLE
Composer doesn't download the latest version

### ISSUE THREAD

**Issue by gaurav1992** [invoiceninja/sdk-php#63]
`composer require invoiceninja/sdk-php`
Running this command doesn't downloaded the latest version of sdk, probably composer is not setup correctly.

**Comment by hillelcoren** [comment]
Hi,

Maybe you're using Composer v2? This repo is still on v1

**Comment by gaurav1992** [comment]
No, I am on version 1.10.7.

**Comment by gaurav1992** [comment]
Any update here?

**Comment by hillelcoren** [comment]
Sorry, no. The SDK is for the v4 app, our current focus is on v5.

**Comment by gaurav1992** [comment]
Yes, any plan to update sdk to v5 shortly?

**Comment by hillelcoren** [comment]
We plan to but not in the immediate future, until then I suggest accessing the API directly

**Comment by turbo124** [comment]
We now track releases in packagist
