### ISSUE TITLE
Is it possible to query invoices by date?

### ISSUE THREAD

**Issue by dph-jan** [invoiceninja/sdk-php#64]
For me,
`Invoice::findByCustomQuery(["invoice_number" => "id123"]);`
returns the correct invoice object, however
`Invoice::findByCustomQuery(["invoice_date" => "2021-06-03"]);`
returns all invoices, just like `Invoice::all();`

Is there any way to query invoices by providing a date or, even better, a date range using the sdk or curl?

**Comment by cilozue** [comment]
Have you tried using findByCustomQuery?

**Comment by turbo124** [comment]
This is now possible in v1.0.2 for v5 of invoice ninja
