### ISSUE TITLE
How to pull data from invoicing.co

### ISSUE THREAD

**Issue by stojankukrika** [invoiceninja/sdk-php#72]
Hu, I tried to use this package but looks like didn't work. I do not see any model which is mention in this package documentation. I tried to use Postman and laravel guzzle client with custom header (X-Ninja-Token) with the token that I generate on invoicing.co but get the error "Invalid token". Can anybody show me direction where and how to start? I am totally confused here.

**Comment by hillelcoren** [comment]
https://stackoverflow.com/a/33526908/497368

**Comment by stojankukrika** [comment]
thank you a loot @hillelcoren !!!
