### ISSUE TITLE
Shouldn’t disable SSL verification by default

### ISSUE THREAD

**Issue by minorOffense** [invoiceninja/sdk-php#75]
The SDK’s default http client disables SSL verification and that’s probably not a good idea. 

I’d suggest removing that setting. If you need to toggle it off (e.g. for tests or local dev) add a flag in the constructor or a debug mode env var. 

https://github.com/invoiceninja/sdk-php/blob/7a644a50be2b5d24863cc03b01cdf84f62011d6d/src/InvoiceNinja.php#L174

**Comment by turbo124** [comment]
Thanks

#78
