### ISSUE TITLE
Unnecessary response code check 

### ISSUE THREAD

**Issue by minorOffense** [invoiceninja/sdk-php#77]
Guzzle will automatically throw an exception if it doesn't get a success response. You shouldn't have to check for a 200. 

Also there are other valid response codes (like 201 CREATED) that this current implementation wouldn't work with. 

If all you're interested in is if the request was successful and not checking for specific types of success responses you should be able to skip the check all together. 

https://github.com/invoiceninja/sdk-php/blob/7a644a50be2b5d24863cc03b01cdf84f62011d6d/src/InvoiceNinja.php#L198

**Comment by turbo124** [comment]
#78
