### ISSUE TITLE
Cannot use custom_value1 in all() for Clients

### ISSUE THREAD

**Issue by kpirbhai** [invoiceninja/sdk-php#88]
I've tested both my hosted setup and my self-hosted setup ( using fully updated v5-stable branch ).

$client = $ninja->clients->all(['custom_value1' => 'xxx']);

In my self-hosted setup, the above simply returns all clients even though there is a single client with "xxx" in custom_value1 which is verified by the actual content returned.

In the hosted setup, the above returns "Undefined array key 0"

**Comment by turbo124** [comment]
try using 'filter' => 'xxx'

the filter parameter will search the custom value columns,


you'll see here the available filters you can use

https://github.com/invoiceninja/sdk-php#retrieving-models

**Comment by kpirbhai** [comment]
Thanks. I dug way down in the invoice ninja git about an hour ago. I was
coming to that conclusion but hadn't tried yet as I needed to rest my
brain. 😜
