### ISSUE TITLE
Download invoice

### ISSUE THREAD

**Issue by 3tlam** [invoiceninja/sdk-php#90]
Heya

as per the README:
```
If you wanted to download a invoice PDF
    $pdf = $ninja->invoices->bulk("download", ["hash_1"]);
```

This does not work for me :(

Looking into the source (`/app/Http/Controllers/InvoiceController.php`, Line 567), the action should be `bulk_download` and not `download`? Also the `count() > 1` should be `count() >0` or `>= 1`, as per the README I can "download" one inovice?
Changing this, there is no browser "download" per se, instead an email is generated for the customer?
Is this the idea?

Thanks for your help!

**Comment by turbo124** [comment]
#91

This is now possible using the following:

```php
$download = $ninja->invoices->download(['hashed_id']);
```

Ensure you pass an id in a array

**Comment by 3tlam** [comment]
Heya @turbo124 

Thank for the quick fix, but it does not really work for me?
It just returns an array of the invoice?

And maybe update die README accordingly, as this function is not supported?

Best

**Comment by turbo124** [comment]
@3tlam 

have you run composer update to pull in the new version?

**Comment by 3tlam** [comment]
Yep, sure - otherwise I‘d have gotten an error for an unspecified method
What should be happening?

**Comment by turbo124** [comment]
not sure, i wrote tests for this and it passes as expected for me:

https://github.com/invoiceninja/sdk-php/blob/f69f00186398fd5cededea29fc59eaf2ac252936/tests/InvoicesTest.php#L184

can you paste a snippet of your code?

**Comment by TheJenne18** [comment]
Hi, I'm running on the latest version (1.0.6) and we have the same issue as described aboved.

**Comment by TheJenne18** [comment]
I've opened 2 Pull Requests, they both have the same result. You can choose which one is the better fit 😄

**Comment by turbo124** [comment]
@TheJenne18 can you confirm that your Invoice Ninja installation is at 5.5.21 these additional methods - whilst valid - should not be needed if you are using the latest version of Invoice Ninja
