### ISSUE TITLE
Update overwrites entire client

### ISSUE THREAD

**Issue by KRens** [invoiceninja/sdk-php#94]
Maybe it's usefull to add to the readme documentation file that running "update", empties the entire client if a field is not present.
I accidentally erased all details of a user:

$client = $ninja->clients->update($clients['data'][0]['id'], ['name' => 'A new client name updated']);

![image](https://user-images.githubusercontent.com/3227067/196347630-ed45d412-e1b8-48c6-b61a-7d90d78d11d8.png)

**Comment by turbo124** [comment]
Updated here:

#95
